Repository cjdrkd7668/SsangYongLivingProject, pull requests merged in 2021-03, with the labels that each got.

#5 알림 페이지 구현
  SsangYongLiving/src/main/java/com/test/living/group/GroupController.java
  SsangYongLiving/src/main/webapp/WEB-INF/tiles.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/notice.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/groupasset.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/groupheader.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/layout/groupmain.jsp
  SsangYongLiving/src/main/webapp/resources/images/group/cart.png
  SsangYongLiving/src/main/webapp/resources/images/group/chat.png
  SsangYongLiving/src/main/webapp/resources/images/group/coupon.png
  SsangYongLiving/src/main/webapp/resources/images/group/notice.png
  SsangYongLiving/src/main/webapp/resources/images/group/open.png
  SsangYongLiving/src/main/webapp/resources/images/group/post.png
  SsangYongLiving/target/classes/com/test/living/group/GroupController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#6 css 추가
  SsangYongLiving/src/main/webapp/resources/css/globalgroup.css
Labels: enhancement

#9 홈페이지 favicon 추가
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/asset.jsp
  SsangYongLiving/src/main/webapp/resources/images/favicon.ico
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#13 '냉장고 털기' 메인 화면 구현
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/tiles.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/home.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/header.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/recipeasset.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/index.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/layout/recipemain.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/index.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/main.jsp
  SsangYongLiving/src/main/webapp/resources/css/address.css
  SsangYongLiving/src/main/webapp/resources/css/main.css
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
Labels: enhancement

#14 공동구매글 상세페이지 UI 구현
  .gitignore
  SsangYongLiving/.classpath
  SsangYongLiving/src/main/java/com/test/living/group/GroupController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/community_list.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/view.jsp
  SsangYongLiving/src/main/webapp/resources/images/group/product001.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product002.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product003.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product004.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product005.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product006.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product007.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product008.jpg
  SsangYongLiving/src/main/webapp/resources/images/group/product009.jpg
  SsangYongLiving/target/classes/com/test/living/group/GroupController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#15 냉장고 최신화 화면 구현중(1)
  .gitignore
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/header.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/main.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/src/main/webapp/resources/images/ingredient-beef.png
  SsangYongLiving/src/main/webapp/resources/images/ingredient-chicken.png
  SsangYongLiving/src/main/webapp/resources/images/ingredient-saesonge.png
  SsangYongLiving/src/main/webapp/resources/images/recipe-tray.png
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
Labels: on progress

#21 냉장고 최신화 페이지 UI 구현
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#22 냉장고 최신화 모달 추가
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#23 고수들의 레시피 게시판
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/main.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
Labels: enhancement

#28 레시피 게시판과 레시피 상세 페이지 UI 구현
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/detail.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/src/main/webapp/resources/images/ingredient-pork.png
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#29 레시피 쓰기 UI 구현
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/addRecipe.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/detail.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/src/main/webapp/resources/images/default-image.png
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#31 레시피 이미지 첨부 시 미리보기 추가
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/addRecipe.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/editRecipe.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/renewRefri.jsp
Labels: enhancement

#32 로그인&로그아웃 구현
  SpringBoard/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/java/com/test/living/auth/AuthController.java
  SsangYongLiving/src/main/java/com/test/living/inc/Pagination.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/webapp/WEB-INF/tiles.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/auth/login.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/header.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/target/classes/com/test/living/auth/AuthController.class
  SsangYongLiving/target/classes/com/test/living/inc/Pagination.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#33 레시피 게시판 기능 구현(+페이지네이션 class import)
  SpringBoard/src/main/java/com/test/board/BoardController.java
  SpringBoard/target/classes/com/test/board/BoardController.class
  SsangYongLiving/src/main/java/com/test/living/mapper/recipe.xml
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDTO.java
  SsangYongLiving/src/main/webapp/WEB-INF/mybatis.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/target/classes/com/test/living/mapper/recipe.xml
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDTO.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#34 레시피 게시판 오류 수정
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
Labels: error fix

#36 레시피 상세 페이지 기능 구현중(1)
  SsangYongLiving/src/main/java/com/test/living/mapper/recipe.xml
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeCommentDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeStockDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeCommentDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeCommentDTO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDTO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeOrderDTO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeStockDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeStockDTO.java
  SsangYongLiving/src/main/webapp/WEB-INF/mybatis.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/detail.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/classes/com/test/living/mapper/recipe.xml
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeCommentDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeStockDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeCommentDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeCommentDTO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDTO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeOrderDTO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeStockDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeStockDTO.class
Labels: on progress

#37 레시피 상세 페이지 기능 구현
  .gitignore
  SpringBoard/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/src/main/java/com/test/living/mapper/recipe.xml
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeCommentDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeCommentDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDAO.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/board.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/detail.jsp
  SsangYongLiving/src/main/webapp/resources/css/recipe.css
  SsangYongLiving/target/classes/com/test/living/mapper/recipe.xml
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeCommentDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeCommentDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDAO.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#41 커뮤니티 글 수정, 삭제 구현
  SsangYongLiving/.classpath
  SsangYongLiving/pom.xml
  SsangYongLiving/src/main/java/com/test/living/group/CommunityDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/GroupController.java
  SsangYongLiving/src/main/java/com/test/living/group/ICommunityDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/SocketHandler.java
  SsangYongLiving/src/main/java/com/test/living/mapper/group.xml
  SsangYongLiving/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/communityEdit.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/communityView.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/viewadd.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/websocket-echo.jsp
  SsangYongLiving/src/main/webapp/resources/css/globalgroup.css
  SsangYongLiving/src/main/webapp/resources/page.html
  SsangYongLiving/target/classes/com/test/living/group/CommunityDAO.class
  SsangYongLiving/target/classes/com/test/living/group/GroupController.class
  SsangYongLiving/target/classes/com/test/living/group/ICommunityDAO.class
  SsangYongLiving/target/classes/com/test/living/group/SocketHandler$1.class
  SsangYongLiving/target/classes/com/test/living/group/SocketHandler.class
  SsangYongLiving/target/classes/com/test/living/mapper/group.xml
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.xml
Labels: enhancement

#42 공동구매 Qna 글쓰기 UI 구현
  SsangYongLiving/src/main/java/com/test/living/group/GroupController.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/add.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/view.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/viewadd.jsp
  SsangYongLiving/target/classes/com/test/living/group/GroupController.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#44 공동구매 알림 페이지 구현, 상세페이지 일부 기능 구현
  SsangYongLiving/pom.xml
  SsangYongLiving/src/main/java/com/test/living/group/CouponDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/CouponDTO.java
  SsangYongLiving/src/main/java/com/test/living/group/GroupBuyingPostDTO.java
  SsangYongLiving/src/main/java/com/test/living/group/GroupController.java
  SsangYongLiving/src/main/java/com/test/living/group/ICouponDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/INoticeDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/IQnaDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/NoticeDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/NoticeDTO.java
  SsangYongLiving/src/main/java/com/test/living/group/QnaDAO.java
  SsangYongLiving/src/main/java/com/test/living/group/QnaDTO.java
  SsangYongLiving/src/main/java/com/test/living/group/SearchDTO.java
  SsangYongLiving/src/main/java/com/test/living/mapper/group.xml
  SsangYongLiving/src/main/webapp/WEB-INF/mybatis.xml
  SsangYongLiving/src/main/webapp/WEB-INF/spring/root-context.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/add.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/notice.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/search.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/group/view.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/inc/groupheader.jsp
  SsangYongLiving/src/main/webapp/resources/css/globalgroup.css
  SsangYongLiving/target/classes/com/test/living/group/CouponDAO.class
  SsangYongLiving/target/classes/com/test/living/group/CouponDTO.class
  SsangYongLiving/target/classes/com/test/living/group/GroupBuyingPostDTO.class
  SsangYongLiving/target/classes/com/test/living/group/GroupController.class
  SsangYongLiving/target/classes/com/test/living/group/ICouponDAO.class
  SsangYongLiving/target/classes/com/test/living/group/INoticeDAO.class
  SsangYongLiving/target/classes/com/test/living/group/IQnaDAO.class
  SsangYongLiving/target/classes/com/test/living/group/NoticeDAO.class
  SsangYongLiving/target/classes/com/test/living/group/NoticeDTO.class
  SsangYongLiving/target/classes/com/test/living/group/QnaDAO.class
  SsangYongLiving/target/classes/com/test/living/group/QnaDTO.class
  SsangYongLiving/target/classes/com/test/living/group/SearchDTO.class
  SsangYongLiving/target/classes/com/test/living/mapper/group.xml
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.xml
Labels: enhancement

#45 레시피 쓰기 기능 추가
  .gitignore
  SpringBoard/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
  SsangYongLiving/.classpath
  SsangYongLiving/src/main/java/com/test/living/mapper/recipe.xml
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeStockDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IingredientDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IngredientDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IngredientDTO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/MultiRowIngredient.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeStockDAO.java
  SsangYongLiving/src/main/webapp/WEB-INF/mybatis.xml
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/addRecipe.jsp
  SsangYongLiving/target/classes/com/test/living/mapper/recipe.xml
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeStockDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IingredientDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IngredientDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IngredientDTO.class
  SsangYongLiving/target/classes/com/test/living/recipe/MultiRowIngredient.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeStockDAO.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement

#46 레시피 수정 기능
  SsangYongLiving/src/main/java/com/test/living/mapper/recipe.xml
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/IRecipeStockDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeController.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeOrderDAO.java
  SsangYongLiving/src/main/java/com/test/living/recipe/RecipeStockDAO.java
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/addRecipe.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/detail.jsp
  SsangYongLiving/src/main/webapp/WEB-INF/views/recipe/editRecipe.jsp
  SsangYongLiving/target/classes/com/test/living/mapper/recipe.xml
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/IRecipeStockDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeController.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeOrderDAO.class
  SsangYongLiving/target/classes/com/test/living/recipe/RecipeStockDAO.class
  SsangYongLiving/target/m2e-wtp/web-resources/META-INF/maven/com.test/board/pom.properties
Labels: enhancement
